### ISSUE TITLE
Unrecognized variable name 'Longitude'

### ISSUE THREAD

**Issue by mauriiio** [CelsoReyes/zmap7#18]
Good afternoon,

When I load my cataloge, I have the next error.

Error using table2zmapcatalogtable (line 20)
Unrecognized variable name 'Longitude'.

Can you help me? please.

**Comment by CelsoReyes** [comment]
Hi Mauriiio,
I'm sorry for the delay, as I've been on other projects.  In a nutshell, ZMAP doesn't recognize the columns for the file you are trying to import. You can help it by adding column headers to your file.  Please see my answer for issue #20 for more details

I have improved the error message, so that it will help point users in the correct direction.  this will be incorporated into the Master branch soon.
Kind Regards,
Celso

**Comment by mauriiio** [comment]
Thanks a lot. 
Kind Regards
Mauricio. 

Enviado desde Yahoo Mail para Android 
 
  El jue., 17 de oct. de 2019 a la(s) 6:01 a. m., Celso<notifications@github.com> escribió:   
Hi Mauriiio,
I'm sorry for the delay, as I've been on other projects. In a nutshell, ZMAP doesn't recognize the columns for the file you are trying to import. You can help it by adding column headers to your file. Please see my answer for issue #20 for more details

I have improved the error message, so that it will help point users in the correct direction. this will be incorporated into the Master branch soon.
Kind Regards,
Celso
